#!/usr/bin/env python3
"""
THE LAST KUMITE — Title logo conversion.

Converts assets/32730.png (the client's fist-in-ring emblem artwork) into
NES background tiles + a small nametable patch, for use as the actual
title-screen graphic in InitTitle (src/state_machine.asm / src/title.asm).

The source image is 512x480 with a lot of surrounding black margin; only
the fist/ring emblem itself is converted (the "THE LAST KUMITE" / "THE
VIDEOGAME" wordmark baked into the source bitmap is NOT used -- that text
is drawn with the game's own font tiles instead, exactly as before, so it
stays crisp and so "PRESS START" below it can still blink/update
independently). This keeps the converted art's tile budget small (the
emblem alone needs ~42 unique 8x8 tiles at a screen-appropriate size,
comfortably fitting the free local tile range 192-241 in pattern table 0)
and keeps the existing text-rendering pipeline intact.

Color handling: the source art is already essentially flat 4-color art
(black, red, gold, white), so it's quantized directly to the nearest of
those 4 colors. Index 0 (black) is the universal background; indices 1-3
map onto NES sprite palette 0's red/gold family ($16/$27 -- the same
colors Michael's red gi already uses) via the in-game attribute table.

Usage: python3 tools/title_logo_convert.py
Reads:  assets/32730.png
        chr/tiles_bg.chr
Writes: chr/tiles_bg.chr (updated, emblem tiles added at local 192+)
        src/title_logo.inc
"""
import os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), ".")
LOGO_IMAGE = os.path.join(ROOT, "assets", "32730.png")
BG_CHR = os.path.join(ROOT, "chr", "tiles_bg.chr")
OUT_INC = os.path.join(ROOT, "src", "title_logo.inc")

TILE_BYTES = 16
BANK_BYTES = 4096
TILE_BASE = 192
MAX_LOGO_TILES = 50

EMBLEM_CROP = (132, 106, 382, 300)
EMBLEM_SIZE = (64, 64)

PLACE_TILE_X = 12
PLACE_TILE_Y = 2

PALETTE_RGB = [
    (0, 0, 0),
    (168, 16, 0),
    (172, 124, 0),
    (252, 252, 252),
]


def nearest_index(r, g, b):
    best, best_d = 0, None
    for i, (pr, pg, pb) in enumerate(PALETTE_RGB):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if best_d is None or d < best_d:
            best_d, best = d, i
    return best


def tile_to_2bpp(pixel_idx_8x8):
    lo = bytearray(8)
    hi = bytearray(8)
    for y in range(8):
        lo_byte = 0
        hi_byte = 0
        for x in range(8):
            v = pixel_idx_8x8[y][x] & 3
            lo_byte |= (v & 1) << (7 - x)
            hi_byte |= ((v >> 1) & 1) << (7 - x)
        lo[y] = lo_byte
        hi[y] = hi_byte
    return bytes(lo) + bytes(hi)


def main():
    if not os.path.exists(LOGO_IMAGE):
        raise SystemExit(f"ERROR: {LOGO_IMAGE} not found")
    if not os.path.exists(BG_CHR):
        raise SystemExit(f"ERROR: {BG_CHR} not found")

    img = Image.open(LOGO_IMAGE).convert("RGB")
    crop = img.crop(EMBLEM_CROP)
    scaled = crop.resize(EMBLEM_SIZE, Image.LANCZOS)

    w, h = scaled.size
    idx = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            r, g, b = scaled.getpixel((x, y))
            idx[y][x] = nearest_index(r, g, b)

    tiles_w, tiles_h = w // 8, h // 8
    unique_tiles = {}
    tile_order = []
    placement = [[0] * tiles_w for _ in range(tiles_h)]

    for ty in range(tiles_h):
        for tx in range(tiles_w):
            block = tuple(tuple(idx[ty * 8 + y][tx * 8:tx * 8 + 8]) for y in range(8))
            if block in unique_tiles:
                local_i = unique_tiles[block]
            else:
                if len(tile_order) >= MAX_LOGO_TILES:
                    raise SystemExit(
                        f"ERROR: logo needs more than {MAX_LOGO_TILES} unique tiles."
                    )
                local_i = len(tile_order)
                unique_tiles[block] = local_i
                tile_order.append(block)
            placement[ty][tx] = local_i

    print(f"Logo emblem: {len(tile_order)} unique tiles / budget {MAX_LOGO_TILES}")

    with open(BG_CHR, "rb") as f:
        bg_bank = bytearray(f.read())
    if len(bg_bank) != BANK_BYTES:
        raise SystemExit(f"ERROR: {BG_CHR} must be exactly {BANK_BYTES} bytes")

    for i, block in enumerate(tile_order):
        local_idx = TILE_BASE + i
        if local_idx > 241:
            raise SystemExit("ERROR: logo tiles overflow the free 192-241 range")
        offset = local_idx * TILE_BYTES
        bg_bank[offset:offset + TILE_BYTES] = tile_to_2bpp(block)

    with open(BG_CHR, "wb") as f:
        f.write(bg_bank)
    print(f"Updated {BG_CHR} with {len(tile_order)} logo tiles starting at local {TILE_BASE}")

    with open(OUT_INC, "w") as f:
        f.write("; AUTO-GENERATED by tools/title_logo_convert.py — DO NOT EDIT BY HAND\n")
        f.write("; Re-run `make logo` after changing assets/32730.png.\n\n")
        f.write(f"LOGO_TILE_BASE = {TILE_BASE}\n")
        f.write(f"LOGO_TILES_W = {tiles_w}\n")
        f.write(f"LOGO_TILES_H = {tiles_h}\n")
        f.write(f"LOGO_PLACE_X = {PLACE_TILE_X}\n")
        f.write(f"LOGO_PLACE_Y = {PLACE_TILE_Y}\n\n")
        f.write("title_logo_tiles:\n")
        for ty in range(tiles_h):
            row_vals = [str(TILE_BASE + placement[ty][tx]) for tx in range(tiles_w)]
            f.write(f"    .byte {', '.join(row_vals)}\n")
        f.write("\n")

    print(f"Wrote {OUT_INC}")


if __name__ == "__main__":
    main()