#!/usr/bin/env python3
"""
THE LAST KUMITE — Fight stage background conversion.

Converts assets/32732.png (a 256x224 reference background image, exactly
NES screen resolution) into a deduplicated NES background tileset plus a
nametable layout, and writes a ca65 .inc file that LoadFightStage streams
into the PPU instead of the old single-color placeholder bands.

Tiles are quantized by luminance into 4 grayscale-ordered indices; the
in-game attribute table then selects BG1 (ground earth tones, genuinely
olive/brown on real NES hardware) to color them, since the source art's
blue-gray/green coloring doesn't map onto any single existing NES palette
by direct color matching -- luminance-based quantization preserves the
image's shading/silhouette structure instead, which is the standard
approach when source art wasn't authored in the target palette to begin
with.

Usage: python3 tools/bg_convert.py
Reads:  assets/32732.png
        chr/tiles_bg.chr
Writes: chr/tiles_bg.chr (updated)
        src/stage_bg.inc
"""
import os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..")
BG_IMAGE = os.path.join(ROOT, "assets", "32732.png")
BG_CHR = os.path.join(ROOT, "chr", "tiles_bg.chr")
OUT_INC = os.path.join(ROOT, "src", "stage_bg.inc")

TILE_BYTES = 16
BANK_BYTES = 4096
TILES_W, TILES_H = 32, 28
TILE_BASE = 32              # first free local tile index (2-31 used by existing UI borders)
MAX_STAGE_TILES = 96         # fits exactly in the free 32-127 range (alphabet starts at 128)


def luminance(r, g, b):
    return 0.299 * r + 0.587 * g + 0.114 * b


def quantize_by_luminance(img):
    w, h = img.size
    lum = [[0.0] * w for _ in range(h)]
    lo, hi = 255.0, 0.0
    for y in range(h):
        for x in range(w):
            r, g, b = img.getpixel((x, y))[:3]
            v = luminance(r, g, b)
            lum[y][x] = v
            lo, hi = min(lo, v), max(hi, v)
    span = max(hi - lo, 1.0)
    out = [[0] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            t = (lum[y][x] - lo) / span
            idx = min(3, int(t * 4))
            out[y][x] = idx
    return out


def tile_to_2bpp(pixel_idx_8x8):
    lo = bytearray(8)
    hi = bytearray(8)
    for y in range(8):
        lo_byte = 0
        hi_byte = 0
        for x in range(8):
            v = pixel_idx_8x8[y][x] & 3
            lo_byte |= (v & 1) << (7 - x)
            hi_byte |= ((v >> 1) & 1) << (7 - x)
        lo[y] = lo_byte
        hi[y] = hi_byte
    return bytes(lo) + bytes(hi)


def main():
    if not os.path.exists(BG_IMAGE):
        raise SystemExit(f"ERROR: {BG_IMAGE} not found")
    if not os.path.exists(BG_CHR):
        raise SystemExit(f"ERROR: {BG_CHR} not found — run tools/extract_bg_bank.py first")

    img = Image.open(BG_IMAGE).convert("RGB")
    if img.size != (256, 224):
        img = img.resize((256, 224))

    pix_idx = quantize_by_luminance(img)

    unique_tiles = {}
    tile_order = []
    nametable = [[0] * TILES_W for _ in range(TILES_H)]

    for ty in range(TILES_H):
        for tx in range(TILES_W):
            block = tuple(tuple(pix_idx[ty * 8 + y][tx * 8:tx * 8 + 8]) for y in range(8))
            if block in unique_tiles:
                idx = unique_tiles[block]
            elif len(tile_order) < MAX_STAGE_TILES:
                idx = len(tile_order)
                unique_tiles[block] = idx
                tile_order.append(block)
            else:
                def avg(b):
                    return sum(sum(row) for row in b) / 64.0
                target = avg(block)
                idx = min(range(len(tile_order)), key=lambda i: abs(avg(tile_order[i]) - target))
            nametable[ty][tx] = idx

    print(f"Unique background tiles used: {len(tile_order)} / budget {MAX_STAGE_TILES}")

    with open(BG_CHR, "rb") as f:
        bg_bank = bytearray(f.read())
    if len(bg_bank) != BANK_BYTES:
        raise SystemExit(f"ERROR: {BG_CHR} must be exactly {BANK_BYTES} bytes")

    for i, block in enumerate(tile_order):
        tile_bytes = tile_to_2bpp(block)
        local_idx = TILE_BASE + i
        if local_idx > 127:
            raise SystemExit("ERROR: background tiles overflow into the alphabet range (local 128+)")
        offset = local_idx * TILE_BYTES
        bg_bank[offset:offset + TILE_BYTES] = tile_bytes

    with open(BG_CHR, "wb") as f:
        f.write(bg_bank)
    print(f"Updated {BG_CHR} with {len(tile_order)} stage tiles starting at local {TILE_BASE}")

    with open(OUT_INC, "w") as f:
        f.write("; AUTO-GENERATED by tools/bg_convert.py — DO NOT EDIT BY HAND\n")
        f.write("; Re-run `make bg` after changing assets/32732.png.\n\n")
        f.write(f"STAGE_TILE_BASE = {TILE_BASE}\n\n")
        f.write("stage_nametable:\n")
        for ty in range(TILES_H):
            row_vals = [str(TILE_BASE + nametable[ty][tx]) for tx in range(TILES_W)]
            f.write(f"    .byte {', '.join(row_vals)}\n")
        # Attribute table: 64 bytes (8 columns × 8 rows of 4×4 tile blocks).
        # Upper 2 attribute rows (tile rows 0-7)  → palette 0 = sky blues.
        # Lower 6 attribute rows (tile rows 8-27) → palette 1 = earth tones.
        # %00000000 = all four 2×2 quadrants use palette 0.
        # %01010101 = all four 2×2 quadrants use palette 1.
        f.write("\nstage_attribute_table:\n")
        attr_bytes = []
        for attr_row in range(8):       # 8 attribute rows
            if attr_row < 2:
                val = "%00000000"       # palette 0 — sky blues ($11/$21/$31)
            else:
                val = "%01010101"       # palette 1 — earth tones ($08/$18/$28)
            for _col in range(8):       # 8 attribute columns per row
                attr_bytes.append(val)
        # Emit as 8 .byte lines of 8 values each (64 bytes total)
        for i in range(0, 64, 8):
            f.write("    .byte " + ", ".join(attr_bytes[i:i + 8]) + "\n")

    print(f"Wrote {OUT_INC}")


if __name__ == "__main__":
    main()