; THE LAST KUMITE — CHR-ROM Tile Definitions
; This file contains .incbin directives for CHR data
; The actual CHR binary is generated by Python and placed in chr/tiles.chr
; ============================================================================

.include "constants.asm"
.include "zeropage.asm"
.include "macros.asm"

.segment "RODATA"

; CHR-ROM is 8KB (1 bank × 8KB)
; $0000-$0FFF: Background pattern table
; $1000-$1FFF: Sprite pattern table

; Note: CHR data is included as binary via the Makefile build process.
; The Makefile prepends the iNES header and appends chr/tiles.chr to the
; linked PRG-ROM binary to create the final .NES file.
;
; CHR data layout (8KB total):
;
; BACKGROUND TILES ($0000-$0FFF):
;   $00-$01:   Blank / space tiles
;   $02:       Health bar track (empty, borderless -- solid "unlit" black,
;              same color as universal backdrop so consecutive empty tiles
;              blend into one continuous track instead of a row of boxes)
;   $03:       Health bar, fully filled tile -- player (solid $26 orange-red)
;   $04:       Health bar, fully filled tile -- enemy (solid $11 blue)
;   $05-$0B:   Health bar PARTIAL-fill tiles -- player, 1/8..7/8 columns
;              filled left-to-right in $26 orange-red, remainder in track
;              color. Combined with $02 (0/8) and $03 (8/8) this gives the
;              bar 8 sub-steps of resolution per tile (80 steps across the
;              full 10-tile/100 HP bar) so HP drains as one smooth ramp
;              instead of jumping a whole tile at a time. See hud.asm
;              CalcBarEighths / bar-draw loop.
;   $0C-$0F:   UI border tiles (unused, reserved)
;   $10-$11:   Ground tiles
;   $12:       Sky tile
;   $13-$14:   Wall/building tiles
;   $15-$1B:   Health bar PARTIAL-fill tiles -- enemy, same scheme as
;              $05-$0B but filled in $11 blue
;   $1C-$1F:   Reserved
;   $20-$7F:   Stage background tiles
;   $80-$9F:   Alphabet tiles (A-Z)
;   $A0-$A9:   Number tiles (0-9)
;   $AA-$AF:   Punctuation tiles
;   $B0-$BF:   Title screen decorative tiles
;   $C0-$EF:   Reserved
;   $F0-$FF:   Special effect tiles
;
; SPRITE TILES ($1000-$1FFF):
;   $00-$3F:   Michael Rivers animations (16 frames × 4 tiles)
;   $40-$7F:   Lightning animations (16 frames × 4 tiles)
;   $80-$8F:   Hit effect tiles (impact stars)
;   $90-$9F:   Special effect tiles (stun aura, counter flash)
;   $A0-$BF:   Reserved
;   $C0-$EF:   Reserved
;   $F0-$FF:   Solid color tiles (for VS screen portraits)
;
; Each tile is 16 bytes (8 bytes luma + 8 bytes chroma)
