; THE LAST KUMITE — CHR-ROM Tile Definitions
; This file contains .incbin directives for CHR data
; The actual CHR binary is generated by Python and placed in chr/tiles.chr
; ============================================================================

.segment "RODATA"

; CHR-ROM is 8KB (1 bank × 8KB)
; $0000-$0FFF: Background pattern table
; $1000-$1FFF: Sprite pattern table

; Note: CHR data is included as binary via the Makefile build process.
; The Makefile prepends the iNES header and appends chr/tiles.chr to the
; linked PRG-ROM binary to create the final .NES file.
;
; CHR data layout (8KB total):
;
; BACKGROUND TILES ($0000-$0FFF):
;   $00-$01:   Blank / space tiles
;   $02:       Empty health bar segment
;   $03:       Filled health bar segment (red)
;   $04:       Filled health bar segment (blue)
;   $05-$0F:   UI border tiles
;   $10-$11:   Ground tiles
;   $12:       Sky tile
;   $13-$14:   Wall/building tiles
;   $15-$1F:   Reserved
;   $20-$7F:   Stage background tiles
;   $80-$9F:   Alphabet tiles (A-Z)
;   $A0-$A9:   Number tiles (0-9)
;   $AA-$AF:   Punctuation tiles
;   $B0-$BF:   Title screen decorative tiles
;   $C0-$EF:   Reserved
;   $F0-$FF:   Special effect tiles
;
; SPRITE TILES ($1000-$1FFF):
;   $00-$3F:   Michael Rivers animations (16 frames × 4 tiles)
;   $40-$7F:   Lightning animations (16 frames × 4 tiles)
;   $80-$8F:   Hit effect tiles (impact stars)
;   $90-$9F:   Special effect tiles (stun aura, counter flash)
;   $A0-$BF:   Reserved
;   $C0-$EF:   Reserved
;   $F0-$FF:   Solid color tiles (for VS screen portraits)
;
; Each tile is 16 bytes (8 bytes luma + 8 bytes chroma)
